language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: tzVK3Kbklxrbut8PrGPLkBAHSEXrLu7HGck9lVoY61pglG9guzy267Y3aeoOPp1WYT5S4j79bO5GNauHaIlN/syy38IEDbogJg/yZAVvQ0IJdjQLjqGKkHMORrr7jpZREMY0gXcsXeaoaXJGihseTYxzwpBm89nmeX3uF/WCJTAba20iAFZhNp6FvtyUIEJa4w1wh+w3bU2HNfgrHx3NPMQXxxl60y5T7dfA3jyFWnmNIlmQdO83iA3ZG3sYPJzHh/spQrTwrctaz88I4dwhPw4BjKtfsaEpm1vV4Trfl/X8boZZDkY0TuKLU71GsE/L1p+P+YLc8Ly41pTn8s5zuxfyhlTFyt7gYJLJyizdepfYGCSy2+KlrPaT1hpG2W1sBuwcQdxfThKUlYxpJgJtYucx4slRG4FMb7YRqUiAOb5DJO4Zxre7z7w6ulq0HAfh9lvVI+8rllPa41h8XhZf9d8qc0kY9t1Xp252g0Rcl9N6b5BmPOqLZW3eaTxiwZvmXLN/E5O/L7aGc9tei6dMXNkcCDSZemwbYR4REUBphtQPvE4W+1N/fsZRPAL3p6WVSitf32JWhCC7nJ4T9F9FbVzv0ruDRSrBJtR2uffFPo2OSIH/XOA9T77bSQcPrVLmNG3TC5C7uv2tNhDyG894TbCBNd375C7roaQXA2zx/IA=
  on:
    tags: true
    repo: gpp-rnd/gpplot
    python: 3.8
